image: 'node:lts-alpine'

cache:
  key:
    files:
      - pnpm-lock.yaml
    prefix: pnpm
  paths:
    - node_modules/

stages:
  - build
  - deploy
  - publish

build:
  stage: build
  image: 'node:lts-alpine'
  tags:
    - node.js
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm run build
    - cp package.json dist/
    - cp -r node_modules dist/
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  image: docker:20.10.17-dind
  tags:
    - node.js
  variables:
    REGISTRY_PATH: $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
    IMAGE_ID: $(docker images | grep $CI_REGISTRY/$CI_PROJECT_PATH\/$IMAGE_NAME | awk '{print $3}')
  script:
    - echo "$REGISTRY_PWD" | docker login --username $REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker buildx create --use default
    - docker buildx build --platform linux/amd64,linux/arm64 --push -t $REGISTRY_PATH .
    - docker logout

publish:
  stage: publish
  tags:
    - shell
  variables:
    REGISTRY_PATH: $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
  script:
    # - export
    - curl -X PUT -H "content-type:application/json" -H "Cookie:KuboardUsername=${KuboardUsername};KuboardAccessKey=${KuboardAccessKey}" -d '{"kind":"deployments","namespace":"draft","name":"'${CI_PROJECT_NAME}'","images":{"'${CI_REGISTRY_IMAGE}'":"'${REGISTRY_PATH}'"}}' https://kuboard.devflow.ltd/kuboard-api/cluster/Test/kind/CICDApi/admin/resource/updateImageTag